
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
 
platform :ios, '10.0'
 
target 'client' do
  use_unimodules!
  config = use_native_modules!
 
  use_react_native!(:path => config["reactNativePath"])
 
  target 'MyAppTests' do
end
